// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/metric.proto

package metric

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta         *int64                 `protobuf:"varint,3,opt,name=delta,proto3,oneof" json:"delta,omitempty"`
	Value         *float64               `protobuf:"fixed64,4,opt,name=Value,proto3,oneof" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricMessage) Reset() {
	*x = MetricMessage{}
	mi := &file_proto_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricMessage) ProtoMessage() {}

func (x *MetricMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricMessage.ProtoReflect.Descriptor instead.
func (*MetricMessage) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{0}
}

func (x *MetricMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricMessage) GetDelta() int64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *MetricMessage) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type BatchMetricsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricMessage       `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetricsMessage) Reset() {
	*x = BatchMetricsMessage{}
	mi := &file_proto_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetricsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetricsMessage) ProtoMessage() {}

func (x *BatchMetricsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetricsMessage.ProtoReflect.Descriptor instead.
func (*BatchMetricsMessage) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{1}
}

func (x *BatchMetricsMessage) GetMetrics() []*MetricMessage {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_proto_metric_proto protoreflect.FileDescriptor

const file_proto_metric_proto_rawDesc = "" +
	"\n" +
	"\x12proto/metric.proto\x12\x06metric\x1a\x1bgoogle/protobuf/empty.proto\"}\n" +
	"\rMetricMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\x05delta\x18\x03 \x01(\x03H\x00R\x05delta\x88\x01\x01\x12\x19\n" +
	"\x05Value\x18\x04 \x01(\x01H\x01R\x05Value\x88\x01\x01B\b\n" +
	"\x06_deltaB\b\n" +
	"\x06_Value\"F\n" +
	"\x13BatchMetricsMessage\x12/\n" +
	"\ametrics\x18\x01 \x03(\v2\x15.metric.MetricMessageR\ametrics2\xd2\x02\n" +
	"\aMetrcic\x12?\n" +
	"\bV1GetAll\x12\x16.google.protobuf.Empty\x1a\x1b.metric.BatchMetricsMessage\x128\n" +
	"\x06V1Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\x0eV1UpdateMetric\x12\x15.metric.MetricMessage\x1a\x15.metric.MetricMessage\x12O\n" +
	"\x13V1UpdateManyMetrics\x12\x1b.metric.BatchMetricsMessage\x1a\x1b.metric.BatchMetricsMessage\x12;\n" +
	"\vV1GetMetric\x12\x15.metric.MetricMessage\x1a\x15.metric.MetricMessageB\x14Z\x12internal/pb/metricb\x06proto3"

var (
	file_proto_metric_proto_rawDescOnce sync.Once
	file_proto_metric_proto_rawDescData []byte
)

func file_proto_metric_proto_rawDescGZIP() []byte {
	file_proto_metric_proto_rawDescOnce.Do(func() {
		file_proto_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metric_proto_rawDesc), len(file_proto_metric_proto_rawDesc)))
	})
	return file_proto_metric_proto_rawDescData
}

var file_proto_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_metric_proto_goTypes = []any{
	(*MetricMessage)(nil),       // 0: metric.MetricMessage
	(*BatchMetricsMessage)(nil), // 1: metric.BatchMetricsMessage
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_proto_metric_proto_depIdxs = []int32{
	0, // 0: metric.BatchMetricsMessage.metrics:type_name -> metric.MetricMessage
	2, // 1: metric.Metrcic.V1GetAll:input_type -> google.protobuf.Empty
	2, // 2: metric.Metrcic.V1Ping:input_type -> google.protobuf.Empty
	0, // 3: metric.Metrcic.V1UpdateMetric:input_type -> metric.MetricMessage
	1, // 4: metric.Metrcic.V1UpdateManyMetrics:input_type -> metric.BatchMetricsMessage
	0, // 5: metric.Metrcic.V1GetMetric:input_type -> metric.MetricMessage
	1, // 6: metric.Metrcic.V1GetAll:output_type -> metric.BatchMetricsMessage
	2, // 7: metric.Metrcic.V1Ping:output_type -> google.protobuf.Empty
	0, // 8: metric.Metrcic.V1UpdateMetric:output_type -> metric.MetricMessage
	1, // 9: metric.Metrcic.V1UpdateManyMetrics:output_type -> metric.BatchMetricsMessage
	0, // 10: metric.Metrcic.V1GetMetric:output_type -> metric.MetricMessage
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metric_proto_init() }
func file_proto_metric_proto_init() {
	if File_proto_metric_proto != nil {
		return
	}
	file_proto_metric_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metric_proto_rawDesc), len(file_proto_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metric_proto_goTypes,
		DependencyIndexes: file_proto_metric_proto_depIdxs,
		MessageInfos:      file_proto_metric_proto_msgTypes,
	}.Build()
	File_proto_metric_proto = out.File
	file_proto_metric_proto_goTypes = nil
	file_proto_metric_proto_depIdxs = nil
}
