// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/metric.proto

package metric

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metrcic_V1GetAll_FullMethodName            = "/metric.Metrcic/V1GetAll"
	Metrcic_V1Ping_FullMethodName              = "/metric.Metrcic/V1Ping"
	Metrcic_V1UpdateMetric_FullMethodName      = "/metric.Metrcic/V1UpdateMetric"
	Metrcic_V1UpdateManyMetrics_FullMethodName = "/metric.Metrcic/V1UpdateManyMetrics"
	Metrcic_V1GetMetric_FullMethodName         = "/metric.Metrcic/V1GetMetric"
)

// MetrcicClient is the client API for Metrcic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetrcicClient interface {
	V1GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BatchMetricsMessage, error)
	V1Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	V1UpdateMetric(ctx context.Context, in *MetricMessage, opts ...grpc.CallOption) (*MetricMessage, error)
	V1UpdateManyMetrics(ctx context.Context, in *BatchMetricsMessage, opts ...grpc.CallOption) (*BatchMetricsMessage, error)
	V1GetMetric(ctx context.Context, in *MetricMessage, opts ...grpc.CallOption) (*MetricMessage, error)
}

type metrcicClient struct {
	cc grpc.ClientConnInterface
}

func NewMetrcicClient(cc grpc.ClientConnInterface) MetrcicClient {
	return &metrcicClient{cc}
}

func (c *metrcicClient) V1GetAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BatchMetricsMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMetricsMessage)
	err := c.cc.Invoke(ctx, Metrcic_V1GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metrcicClient) V1Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Metrcic_V1Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metrcicClient) V1UpdateMetric(ctx context.Context, in *MetricMessage, opts ...grpc.CallOption) (*MetricMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricMessage)
	err := c.cc.Invoke(ctx, Metrcic_V1UpdateMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metrcicClient) V1UpdateManyMetrics(ctx context.Context, in *BatchMetricsMessage, opts ...grpc.CallOption) (*BatchMetricsMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMetricsMessage)
	err := c.cc.Invoke(ctx, Metrcic_V1UpdateManyMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metrcicClient) V1GetMetric(ctx context.Context, in *MetricMessage, opts ...grpc.CallOption) (*MetricMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricMessage)
	err := c.cc.Invoke(ctx, Metrcic_V1GetMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetrcicServer is the server API for Metrcic service.
// All implementations must embed UnimplementedMetrcicServer
// for forward compatibility.
type MetrcicServer interface {
	V1GetAll(context.Context, *emptypb.Empty) (*BatchMetricsMessage, error)
	V1Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	V1UpdateMetric(context.Context, *MetricMessage) (*MetricMessage, error)
	V1UpdateManyMetrics(context.Context, *BatchMetricsMessage) (*BatchMetricsMessage, error)
	V1GetMetric(context.Context, *MetricMessage) (*MetricMessage, error)
	mustEmbedUnimplementedMetrcicServer()
}

// UnimplementedMetrcicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetrcicServer struct{}

func (UnimplementedMetrcicServer) V1GetAll(context.Context, *emptypb.Empty) (*BatchMetricsMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method V1GetAll not implemented")
}
func (UnimplementedMetrcicServer) V1Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method V1Ping not implemented")
}
func (UnimplementedMetrcicServer) V1UpdateMetric(context.Context, *MetricMessage) (*MetricMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method V1UpdateMetric not implemented")
}
func (UnimplementedMetrcicServer) V1UpdateManyMetrics(context.Context, *BatchMetricsMessage) (*BatchMetricsMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method V1UpdateManyMetrics not implemented")
}
func (UnimplementedMetrcicServer) V1GetMetric(context.Context, *MetricMessage) (*MetricMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method V1GetMetric not implemented")
}
func (UnimplementedMetrcicServer) mustEmbedUnimplementedMetrcicServer() {}
func (UnimplementedMetrcicServer) testEmbeddedByValue()                 {}

// UnsafeMetrcicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetrcicServer will
// result in compilation errors.
type UnsafeMetrcicServer interface {
	mustEmbedUnimplementedMetrcicServer()
}

func RegisterMetrcicServer(s grpc.ServiceRegistrar, srv MetrcicServer) {
	// If the following call pancis, it indicates UnimplementedMetrcicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metrcic_ServiceDesc, srv)
}

func _Metrcic_V1GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetrcicServer).V1GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrcic_V1GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetrcicServer).V1GetAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrcic_V1Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetrcicServer).V1Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrcic_V1Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetrcicServer).V1Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrcic_V1UpdateMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetrcicServer).V1UpdateMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrcic_V1UpdateMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetrcicServer).V1UpdateMetric(ctx, req.(*MetricMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrcic_V1UpdateManyMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMetricsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetrcicServer).V1UpdateManyMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrcic_V1UpdateManyMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetrcicServer).V1UpdateManyMetrics(ctx, req.(*BatchMetricsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrcic_V1GetMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetrcicServer).V1GetMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrcic_V1GetMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetrcicServer).V1GetMetric(ctx, req.(*MetricMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrcic_ServiceDesc is the grpc.ServiceDesc for Metrcic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrcic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metric.Metrcic",
	HandlerType: (*MetrcicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "V1GetAll",
			Handler:    _Metrcic_V1GetAll_Handler,
		},
		{
			MethodName: "V1Ping",
			Handler:    _Metrcic_V1Ping_Handler,
		},
		{
			MethodName: "V1UpdateMetric",
			Handler:    _Metrcic_V1UpdateMetric_Handler,
		},
		{
			MethodName: "V1UpdateManyMetrics",
			Handler:    _Metrcic_V1UpdateManyMetrics_Handler,
		},
		{
			MethodName: "V1GetMetric",
			Handler:    _Metrcic_V1GetMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metric.proto",
}
